[tool.black]
line-length = 100
target_version = ['py39', 'py310', 'py311']
skip-string-normalization = true
skip-magic-trailing-comma = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Matplotlib is currently using agg:UserWarning",
]
markers = [
    "rigetti_integration: tests that connect to Quil compiler or QVM.",
    "slow: slow tests that should be skipped by default.",
    "weekly: tests to be run only by weekly CI automation.",
]
